INSERT INTO CATEGORIA (CODIGO, NOME) VALUES (SQ_CATEGORIA.NEXTVAL, 'Notebook');
INSERT INTO CATEGORIA (CODIGO, NOME) VALUES (SQ_CATEGORIA.NEXTVAL, 'Smartphone');
INSERT INTO CATEGORIA (CODIGO, NOME) VALUES (SQ_CATEGORIA.NEXTVAL, 'TV');
INSERT INTO CATEGORIA (CODIGO, NOME) VALUES (SQ_CATEGORIA.NEXTVAL, 'Tablet');


